#!/bin/sh
# postrm script for appstream
set -e

if [ "$1" = "purge" ]; then
    # remove the AppStream global cache
    rm -rf /var/cache/swcatalog/cache
    rmdir /var/cache/swcatalog/ || true

    # remove the AppStream data fetched via APT
    rm -rf /var/lib/swcatalog
fi

# Automatically added by dh_installdeb/13.28ubuntu1
dpkg-maintscript-helper rm_conffile /etc/appstream.conf 1.0.0-1 -- "$@"
# End automatically added section

