#!/bin/sh

set -e

# Automatically added by dh_systemd_start/13.24.2ubuntu1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/13.24.2ubuntu1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ec2-instance-connect-harvest-hostkeys.service' >/dev/null || true
	fi
fi
# End automatically added section


case "$1" in
    purge|remove|abort-install|disappear)
        deb-systemd-helper purge ec2-instance-connect
        # Delete system user
        deluser --system --quiet ec2-instance-connect
        echo "Deleted system user ec2-instance-connect"

        # restart ssh since the drop-in disappeared
        deb-systemd-invoke restart ssh.service
    ;;
    *)
        exit 0
    ;;
esac
