#!/bin/sh
set -e

case "$1" in
    remove)
        # Update grub
        if [ -e /boot/grub/grub.cfg ] && [ -x "$(which update-grub)" ]; then
            update-grub
        fi
    ;;
esac

# Automatically added by dh_installdeb/13.24.2ubuntu1
dpkg-maintscript-helper rm_conffile /etc/init/friendly-recovery.conf 0.2.36\~ -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2ubuntu1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


exit 0
