#!/bin/sh
set -e

# it is now a static service
systemctl disable friendly-recovery.service || :

# Automatically added by dh_installdeb/13.24.2ubuntu1
dpkg-maintscript-helper rm_conffile /etc/init/friendly-recovery.conf 0.2.36\~ -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2ubuntu1
if [ -z "$DPKG_ROOT" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'friendly-recovery.service' 'friendly-recovery.target' >/dev/null || true
fi
# End automatically added section


exit 0
