#!/bin/sh

set -e

chrooted() {
	if [ "$(stat -c %d/%i /)" = "$(stat -Lc %d/%i /proc/1/root 2>/dev/null)" ]; then
		# the devicenumber/inode pair of / is the same as that of
		# /sbin/init's root, so we're *not* in a chroot and hence
		# return false.
		return 1
	fi
	return 0
}

# begin-remove-after: released:trixie
# protective diversion of files moved from / to /usr, to avoid file loss.
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	for f in /bin/fusermount /sbin/mount.fuse; do
		dpkg-divert --package fuse3 --no-rename --divert "$f.usr-is-merged" --remove "$f"
	done
fi
# end-remove-after

case "${1}" in
	configure)
		if ! dpkg-statoverride --list /bin/fusermount3 > /dev/null 2>&1 &&
			! dpkg-statoverride --list /usr/bin/fusermount3 > /dev/null 2>&1
		then
			chmod 4755 /usr/bin/fusermount3
		fi

		modprobe fuse > /dev/null 2>&1 || true

		if [ -x "`which update-initramfs 2>/dev/null`" ]
		then
			update-initramfs -u
		fi
		;;

	abort-upgrade|abort-remove|abort-deconfigure)

		;;

	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac



exit 0
