#!/bin/sh
set -e

# Automatically added by dh_installdeb/13.31ubuntu1
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.fwupd.conf 2.0.6-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fwupd.conf 2.0.6-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fwupd/ata.conf 2.0.6-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fwupd/daemon.conf 2.0.6-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fwupd/msr.conf 2.0.6-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fwupd/redfish.conf 2.0.6-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fwupd/remotes.d/dell-esrt.conf 2.0.6-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fwupd/remotes.d/fwupd.conf 2.0.6-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fwupd/remotes.d/vendor.conf 2.0.6-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fwupd/thunderbolt.conf 2.0.6-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fwupd/uefi.conf 2.0.6-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fwupd/uefi_capsule.conf 2.0.6-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fwupd/upower.conf 2.0.6-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/modules-load.d/fwupd-msr.conf 2.0.6-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/modules-load.d/fwupd-platform-integrity.conf 2.0.6-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pki/fwupd/GPG-KEY-Hughski-Limited 2.0.6-5\~ -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.31ubuntu1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.31ubuntu1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'fwupd-refresh.timer' >/dev/null || true
	fi
fi
# End automatically added section


if [ "$1" = purge ]; then
    rm -rf /var/lib/fwupd /var/cache/fwupd /var/cache/fwupdmgr
    rm -f /var/cache/app-info/xmls/fwupd.xml
fi
