#!/bin/sh
set -e

# Automatically added by dh_installdeb/13.31ubuntu1
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.fwupd.conf 2.0.6-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fwupd.conf 2.0.6-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fwupd/ata.conf 2.0.6-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fwupd/daemon.conf 2.0.6-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fwupd/msr.conf 2.0.6-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fwupd/redfish.conf 2.0.6-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fwupd/remotes.d/dell-esrt.conf 2.0.6-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fwupd/remotes.d/fwupd.conf 2.0.6-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fwupd/remotes.d/vendor.conf 2.0.6-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fwupd/thunderbolt.conf 2.0.6-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fwupd/uefi.conf 2.0.6-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fwupd/uefi_capsule.conf 2.0.6-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fwupd/upower.conf 2.0.6-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/modules-load.d/fwupd-msr.conf 2.0.6-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/modules-load.d/fwupd-platform-integrity.conf 2.0.6-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pki/fwupd/GPG-KEY-Hughski-Limited 2.0.6-5\~ -- "$@"
# End automatically added section


# 1.3.2 had fwupd-refresh.service and fwupd.service both claiming
# this directory, but fwupd-refresh.service used DynamicUser directive
# meaning no other unit could access it.
if [ -L /var/cache/fwupd ]; then
    rm -f /var/cache/fwupd
fi
