#!/bin/sh
set -e
# Automatically added by dh_installalternatives/13.28ubuntu1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ]; then
        update-alternatives --install /usr/bin/telnet telnet /usr/bin/inetutils-telnet 150 \
            --slave /usr/share/man/man1/telnet.1.gz telnet.1.gz /usr/share/man/man1/inetutils-telnet.1.gz
fi
# End automatically added section
