#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2ubuntu1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/irqbalance" ] ; then
	chmod -x "/etc/init.d/irqbalance" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d irqbalance remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.2ubuntu1
dpkg-maintscript-helper rm_conffile /etc/init/irqbalance.conf 1.2.0-0.1\~ -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2ubuntu1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2ubuntu1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'irqbalance.service' >/dev/null || true
	fi
fi
# End automatically added section
