#!/bin/sh

set -e

case "$1" in
    configure)
        vgcfgbackup >/dev/null 2>&1 || :
        if dpkg --compare-versions "$2" lt "2.02.133~"; then
            deb-systemd-helper purge lvm2-activation-early.service lvm2-activation.service >/dev/null
            deb-systemd-helper unmask lvm2-activation-early.service lvm2-activation.service >/dev/null
        fi
        if dpkg --compare-versions "$2" lt "2.03.02-3~"; then
            deb-systemd-helper purge lvm2-lvmetad.socket >/dev/null
            deb-systemd-helper unmask lvm2-lvmetad.socket >/dev/null
            update-rc.d -f lvm2-lvmetad remove
        fi
        if dpkg --compare-versions "$2" lt "2.03.16-2~"; then
            update-rc.d -f lvm2 remove
            update-rc.d -f lvm2-lvmpolld remove
        fi
    ;;
esac

# Automatically added by dh_installtmpfiles/13.28ubuntu1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "$(command -v systemd-tmpfiles)" ]; then
		systemd-tmpfiles ${DPKG_ROOT:+--root="$DPKG_ROOT"} --create lvm2.conf || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdeb/13.28ubuntu1
dpkg-maintscript-helper rm_conffile /etc/init.d/lvm2-lvmetad 2.03.02-2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init.d/lvm2 2.03.16-2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init.d/lvm2-lvmpolld 2.03.16-2\~ -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.28ubuntu1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'blk-availability.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'blk-availability.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'blk-availability.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'blk-availability.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.28ubuntu1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'lvm2-monitor.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'lvm2-monitor.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'lvm2-monitor.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'lvm2-monitor.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.28ubuntu1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		deb-systemd-invoke start 'blk-availability.service' 'lvm2-monitor.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.28ubuntu1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'lvm2-lvmpolld.socket' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'lvm2-lvmpolld.socket'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'lvm2-lvmpolld.socket' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'lvm2-lvmpolld.socket' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.28ubuntu1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'lvm2-lvmpolld.socket' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
