#!/bin/sh

set -e

case "$1" in
    remove)
        vgcfgbackup >/dev/null 2>&1 || :
    ;;
esac

# Automatically added by dh_installsystemd/13.28ubuntu1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'lvm2-lvmpolld.socket' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.28ubuntu1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'blk-availability.service' 'lvm2-monitor.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdeb/13.28ubuntu1
dpkg-maintscript-helper rm_conffile /etc/init.d/lvm2-lvmetad 2.03.02-2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init.d/lvm2 2.03.16-2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init.d/lvm2-lvmpolld 2.03.16-2\~ -- "$@"
# End automatically added section


exit 0
