#! /bin/sh
# Copyright © 2001,2002 Mario Jou/3en <joussen@debian.org>
# Copyright © 2006-2008 Martin F. Krafft <madduck@debian.org>
# Distributable under the terms of the GNU GPL version 2.
#
set -e

case "${1:-}" in
    remove)
	if command -v update-initramfs >/dev/null 2>&1; then
	    update-initramfs -u
	fi
    ;;

  purge)
    rm -f /etc/default/mdadm /etc/mdadm.conf /etc/mdadm/mdadm.conf
    ;;

esac

[ -d /run/systemd/system ] && systemctl --system daemon-reload >/dev/null || :

# Automatically added by dh_installdeb/13.31ubuntu1
dpkg-maintscript-helper rm_conffile /etc/cron.d/mdadm 4.2\+20230227-1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/cron.daily/mdadm 4.2\+20230227-1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init.d/mdadm 4.2\+20230227-1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init.d/mdadm-waitidle 4.2\+20230227-1\~ -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.31ubuntu1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.31ubuntu1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'mdcheck_continue.timer' 'mdcheck_start.timer' 'mdmonitor-oneshot.timer' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.31ubuntu1
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

