#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.31ubuntu1
dpkg-maintscript-helper rm_conffile /etc/cron.d/mdadm 4.2\+20230227-1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/cron.daily/mdadm 4.2\+20230227-1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init.d/mdadm 4.2\+20230227-1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init.d/mdadm-waitidle 4.2\+20230227-1\~ -- "$@"
# End automatically added section
