#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.31ubuntu1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'multipathd-queueing.service' 'multipathd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdeb/13.31ubuntu1
dpkg-maintscript-helper rm_conffile /etc/init.d/multipath-tools 0.9.4-7\~ multipath-tools -- "$@"
# End automatically added section
