#!/bin/sh
set -e

# begin-remove-after: released:forky
if [ "$1" = upgrade ] && dpkg --compare-versions "$2" lt-nl 1:9.8p1-1~; then
	# Temporarily divert the new sshd binary, since OpenSSH 9.8 moved
	# part of its responsibilities to sshd-session, and unpacking the
	# new sshd to its normal path would break new connections.  We'll
	# remove this diversion when we're ready to restart the listener
	# process.
	#
	# Since we're trying to divert a file shipped in this package, we
	# use a package name that we know doesn't ship /usr/sbin/sshd.
	dpkg-divert --package openssh-client --add --no-rename \
		--divert /usr/sbin/sshd.session-split /usr/sbin/sshd
fi
# end-remove-after

# Automatically added by dh_installdeb/13.31ubuntu1
dpkg-maintscript-helper rm_conffile /etc/network/if-up.d/openssh-server 1:7.9p1-1\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.31ubuntu1
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/ssh" ] ; then
	chmod +x "/etc/init.d/ssh" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.31ubuntu1
if [ -z "$DPKG_ROOT" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'ssh.socket' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.31ubuntu1
if [ -z "$DPKG_ROOT" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'ssh.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.31ubuntu1
if [ -z "$DPKG_ROOT" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'rescue-ssh.target' >/dev/null || true
fi
# End automatically added section


exit 0
