#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.31ubuntu1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'sshd-keygen.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.31ubuntu1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'rescue-ssh.target' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.31ubuntu1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'ssh.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.31ubuntu1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'ssh.socket' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.31ubuntu1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/ssh" ] ; then
	invoke-rc.d --skip-systemd-native ssh stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.31ubuntu1
dpkg-maintscript-helper rm_conffile /etc/network/if-up.d/openssh-server 1:7.9p1-1\~ -- "$@"
# End automatically added section
