#!/bin/sh
set -e
# Automatically added by dh_installinit/13.31ubuntu1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/open-vm-tools" ] ; then
	chmod -x "/etc/init.d/open-vm-tools" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d open-vm-tools remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.31ubuntu1
dpkg-maintscript-helper rm_conffile /etc/vmware-tools/guestproxy-ssl.conf 2:11.3.0-1\~ open-vm-tools -- "$@"
dpkg-maintscript-helper rm_conffile /etc/vmware-tools/vm-support 2:11.3.0-1\~ open-vm-tools -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.31ubuntu1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.31ubuntu1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'vgauth.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.31ubuntu1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.31ubuntu1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'open-vm-tools.service' >/dev/null || true
	fi
fi
# End automatically added section
