#!/bin/sh

set -e

case "${1}" in
	remove)
		# Remove the compatibility symlinks
		if [ -L '/bin/plymouth' ]; then
			rm /bin/plymouth
		fi
		if [ -L '/sbin/plymouthd' ]; then
			rm /sbin/plymouthd
		fi
		dpkg-trigger update-initramfs
		;;
	purge)
		rm -f /var/lib/plymouth/boot-duration
		;;
	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

		;;

	*)
		echo "postrm called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

# Automatically added by dh_installinit/13.31ubuntu1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/plymouth-log" ] ; then
	chmod -x "/etc/init.d/plymouth-log" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d plymouth-log remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit/13.31ubuntu1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/plymouth" ] ; then
	chmod -x "/etc/init.d/plymouth" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d plymouth remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.31ubuntu1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


exit 0
