#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.31ubuntu1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'polkit-agent-helper.socket' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.31ubuntu1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'polkit.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installxmlcatalogs/UNDECLARED
if [ "$1" = "remove" ] || [ "$1" = "upgrade" ]; then
	update-xmlcatalog --del --type public --id "-//freedesktop//DTD PolicyKit Policy Configuration 1.0//EN" --root || true
	update-xmlcatalog --del --type system --id "http://www.freedesktop.org/standards/PolicyKit/1.0/policyconfig.dtd" --root || true

	update-xmlcatalog --del --type public --id "-//freedesktop//DTD PolicyKit Policy Configuration 1.0//EN" --package polkitd || true
	update-xmlcatalog --del --type system --id "http://www.freedesktop.org/standards/PolicyKit/1.0/policyconfig.dtd" --package polkitd || true

fi
# End automatically added section
