#!/bin/sh
set -e

PKG="pollinate"
if [ "$1" = "purge" ]; then
	rm -rf /var/lib/$PKG /var/cache/$PKG /etc/default/$PKG
	deluser --quiet --system $PKG > /dev/null || true
fi

# Automatically added by dh_installdeb/13.31ubuntu1
dpkg-maintscript-helper rm_conffile /etc/init/pollinate.conf 4.27-0ubuntu1\~ pollinate -- "$@"
dpkg-maintscript-helper rm_conffile /etc/pollinate/entropy.ubuntu.com.pem 4.33-4ubuntu6\~ pollinate -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.31ubuntu1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.31ubuntu1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'pollinate.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_apparmor/5.0.0~beta1-0ubuntu5
if [ "$1" = "purge" ] && ! [ -e "/etc/apparmor.d/pollinate" ] ; then
    rm -f "/etc/apparmor.d/disable/pollinate" || true
    rm -f "/etc/apparmor.d/force-complain/pollinate" || true
    rm -f "/etc/apparmor.d/local/pollinate" || true
    rm -f /var/cache/apparmor/*/"pollinate" || true
    rmdir /etc/apparmor.d/disable 2>/dev/null || true
    rmdir /etc/apparmor.d/local   2>/dev/null || true
    rmdir /etc/apparmor.d         2>/dev/null || true
fi
# End automatically added section

