#! /bin/sh

set -e

case "$1" in
    configure)
    files=$(LC_ALL=C.UTF8 dpkg -L libpython3.14-stdlib:amd64 | sed -n '/^\/usr\/lib\/python3.14\/.*\.py$/p')
    if [ -n "$files" ]; then
	/usr/bin/python3.14 -E -S /usr/lib/python3.14/py_compile.py $files
	if grep -sq '^byte-compile[^#]*optimize' /etc/python/debian_config; then
	    /usr/bin/python3.14 -E -S -O /usr/lib/python3.14/py_compile.py $files
	fi
    else
	echo >&2 "python3.14: can't get files for byte-compilation"
    fi
esac



exit 0
