#!/bin/sh

set -e

if [ "$1" = "remove" ] ; then
	update-alternatives --remove jsonpointer /usr/bin/python3-jsonpointer
fi


# Automatically added by dh_python3
if command -v py3clean >/dev/null 2>&1 && python3 -c 'pass' 2>/dev/null; then
	py3clean -p python3-json-pointer 
else
	dpkg -L python3-json-pointer | sed -En -e '/^(.*)\/(.+)\.py$/s,,rm "\1/__pycache__/\2".*,e'
	find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

# End automatically added section


exit 0
