#!/bin/sh -e

case "$1" in
    remove)
        # Unload ufw (will only happen if enabled)
        if [ -x /usr/lib/ufw/ufw-init ]; then
            /usr/lib/ufw/ufw-init stop || true
        fi
        ;;
esac

# Automatically added by dh_installdeb/13.24.2ubuntu1
dpkg-maintscript-helper rm_conffile /etc/init/ufw.conf 0.35-5\~ ufw -- "$@"
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/ufw 0.34-1\~ ufw -- "$@"
# End automatically added section

# Automatically added by dh_python3
if command -v py3clean >/dev/null 2>&1 && python3 -c 'pass' 2>/dev/null; then
	py3clean -p ufw 
else
	dpkg -L ufw | sed -En -e '/^(.*)\/(.+)\.py$/s,,rm "\1/__pycache__/\2".*,e'
	find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

# End automatically added section

