#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.31ubuntu1
dpkg-maintscript-helper rm_conffile /etc/cron.daily/update-notifier-common 3.192.34\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/cron.weekly/update-notifier-common 3.192.34\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/update-motd.d/20-cpu-checker 0.110.1ubuntu1 -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.31ubuntu1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.31ubuntu1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'update-notifier-download.timer' 'update-notifier-motd.timer' >/dev/null || true
	fi
fi
# End automatically added section
