#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.2ubuntu1
dpkg-maintscript-helper rm_conffile /etc/X11/Xsession.d/60xdg-user-dirs-update -- "$@"
# End automatically added section
# Automatically added by dh_installsystemduser/13.24.2ubuntu1
if [ "$1" = "purge" ]; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/usr/bin/deb-systemd-helper" ] ; then
		deb-systemd-helper --user purge 'xdg-user-dirs.service' >/dev/null || true
	fi
fi
# End automatically added section
